name: Run Behave Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  behave:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: ✅ Run Behave Tests with HTML report
        run: |
          source .venv/bin/activate
          mkdir -p reports/
          behave -f behave_html_formatter:HTMLFormatter -o reports/report.html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: behave-html-report
          path: reports/

      - name: Upload Log File
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: logs/
